# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       voicecall-ui-reference

# >> macros
# << macros

Summary:    Dialer UI for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      Communications/Telephony
License:    BSD
URL:        https://github.com/nemomobile/voicecall-ui-reference
Source0:    %{name}-%{version}.tar.bz2
Source100:  voicecall-ui-reference.yaml
Requires:   voicecall-core
Requires:   tone-generator
Requires:   commhistory-daemon
Requires:   libcommhistory-qt5-declarative
Requires:   mapplauncherd-booster-qtcomponents-qt5
Requires:   qt-components-qt5
Requires:   nemo-qml-plugin-contacts-qt5
Requires:   nemo-qml-plugin-thumbnailer-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  desktop-file-utils
Provides:   meego-handset-dialer >= 0.24
Obsoletes:   meego-handset-dialer < 0.24

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
mkdir -p %{buildroot}%{_libdir}/systemd/user/user-session.target.wants
ln -s ../voicecall-ui-prestart.service %{buildroot}%{_libdir}/systemd/user/user-session.target.wants/
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/voicecall-ui
%{_datadir}/voicecall-ui/qml
%{_datadir}/applications/voicecall-ui.desktop
%{_datadir}/dbus-1/services/org.nemomobile.voicecall.ui.service
%{_libdir}/systemd/user/voicecall-ui-prestart.service
%{_libdir}/systemd/user/user-session.target.wants/voicecall-ui-prestart.service

# >> files
# << files
