# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       voicecall-ui-reference

# >> macros
# << macros

Summary:    Dialer UI for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      Communications/Telephony
License:    BSD
URL:        https://github.com/nemomobile/voicecall-ui-reference
Source0:    %{name}-%{version}.tar.bz2
Source100:  voicecall-ui-reference.yaml
Requires:   voicecall-core
Requires:   tone-generator
Requires:   commhistory-daemon
Requires:   libcommhistory-declarative
Requires:   mapplauncherd-booster-qtcomponents
Requires:   qt-components
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  desktop-file-utils
Provides:   meego-handset-dialer >= 0.24
Obsoletes:   meego-handset-dialer < 0.24

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/voicecall-ui
%{_datadir}/voicecall-ui/qml
%{_datadir}/applications/voicecall-ui.desktop
%config %{_sysconfdir}/xdg/autostart/voicecall-ui-prestart.desktop
%{_libdir}/systemd/user/voicecall-ui-prestart.service
# >> files
# << files
